---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_database: "logs"
clickhouse_table: "syslog"
syslog_path: "/var/log/syslog"
